language: node_js
node_js:
  - "8"

cache:
  directories:
    - "node_modules"

branches:
  only:
    - master

install:
  - npm install
  - npm run generate:gh-pages

script:
  - echo "Skipping tests"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_ACCESS_TOKEN # セキュアとマークされたアクセストークンを travis-ci.org のダッシュボードに設定してください。https://docs.travis-ci.com/user/deployment/pages/#Setting-the-GitHub-token
  target-branch: gh-pages
  local-dir: dist
  on:
    branch: master

notifications:
  slack:
    secure: "j4jCIg26QvpfbFho5WgpF4UnqVItlKklSgT3ysPwn6BYCXzdopbaIDkyBNz3UbtcwVv4evzsJV183GalP+8/O2eZVoDdnjXYs0JKqJCwjmlbWv28FJY+uCCmFLT/D4XZ87YkqXFiJnB0SGiGRvV+/GFYqZ/BnJeG7JDVnmN75CuyZtOi3mi9XUVPqXuAvAFwlLEOnYhfLO6+fTrQjCliNyje9qvcZquuwEuFr44+iy0ua3scOzUtuMrlnCU990a3dm2KQXF85Zqu0lquNshbvTVooTlkQ9weI7Du0f3QBfyoDrk4ZOFwSvrLNrqf70LOt2wCRB63CCakXIYFH8XB04UUQGj8pVJqKCbqG9PqzqFM4OuOMqr+SN/fONOTK8mSCxcTbo4aqAsv1nY+08SsE5Vr076Wg1EExCYPog0Ms8GAo1hAV+La+T9SR27gUscjvy4pZbXTYJcKr46gR5B80u5nT1/jaljJUKljH4POxYbYcpQbuWSJ3QUZ+42wc8Ms4lR51u7xKT/1tv5k5DULsBi6fQu8JYmEXoMTRTaEZfFpOW3WI0WT9luHC8CWLcsB24Au1e4U25NtyUW8Dh2z8lAbS5Elw4HqjvKUFv2IcvTpR8FQwTkBu8Kf30m90IpHfESmcVxNIPxXmnL7mUeF3270+1l76W/YV/Ar/NMm7AE="
